name: test

on: 
  push:
  schedule:
  - cron: '40-59 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pip
        run: |
            python -m pip install --upgrade pip
      - name: Install requests
        run: |
            pip install requests
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 签到预报 
          body: "success"
          to: samzhanghan@qq.com
          from: GitHub Actions
          content_type: text/html
      - name: 'Working'
        env:
          MOBILE: ${{ secrets.MOBILE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LNGLAT: ${{ secrets.LNGLAT }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run:
            python yiban.py
